Test ID: network_failure_packet_delay_8
Test: network_failure_packet_delay
Iteration: 8
Start Time: 2024-11-15 14:35:23.578708
network_failure_packet_delay_8 - Exception: DistributedClient.__init__() got an unexpected keyword argument 'servers'
Result: FAIL
End Time: 2024-11-15 14:35:23.578728
